global using Telegram.Bot;
global using PC.Common.Services;
global using Telegram.Bot.Types;
global using PC.Store.Repositories;
global using PC.Models.Entities;
global using Microsoft.Extensions.DependencyInjection;
global using PC.Models.Enums;
global using Microsoft.Extensions.Configuration;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.Extensions.Options;
global using PC.Common.Commands.Base;
global using Telegram.Bot.Types.Enums;
global using Telegram.Bot.Types.ReplyMarkups;
global using CryptoHelper;
global using PC.Common.PassingType;
global using PC.Common.Commands;
global using PC.Common.Models;
global using AutoMapper;
global using PC.Common.Services;
global using PC.Common.ApiClients;
global using PC.Common.Commands.AddressCommands;
global using PC.Common.Commands.ProfileCommand;
global using AddressDaData = Dadata.Model.Address;
global using Address = PC.Models.Entities.Address;
global using Dadata;
global using Dadata.Model;